// Generado automáticamente por generar_catalogo.py — no editar a mano
// Última actualización: 2026-09-02 00:44
// Organizado por categoría para mayor claridad
const productos = [
  // ===== FÚTBOL =====
  {
    "id": "alnassr-cr7",
    "nombre": "Al Nassr - Cristiano Ronaldo #7",
    "categoria": "futbol",
    "precio": 18,
    "precio_anterior": 20,
    "moneda": "USD",
    "imagen": "Futbol/Cr7alhh.png",
    "url": "Cr7al.html",
    "nuevo": true,
    "fecha_agregado": "2026-08-07",
    "es_novedad": true,
    "en_oferta": true
  },
  {
    "id": "barcelona-lamineyamal",
    "nombre": "FC Barcelona - Lamine Yamal #10",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Barcelona/lamineyamal-back.png",
    "url": "barcelona-lamineyamal.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "bayern-kane",
    "nombre": "FC Bayern - Kane #9",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Bayern/front-generic.jpg",
    "url": "bayern-kane.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "bayern-luisdiaz",
    "nombre": "FC Bayern - Luis Díaz #14",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Bayern/luisdiaz-back.jpg",
    "url": "bayern-luisdiaz.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "francia-mbappe",
    "nombre": "Francia - Mbappé #10",
    "categoria": "futbol",
    "precio": 18,
    "precio_anterior": 20,
    "moneda": "USD",
    "imagen": "Futbol/Mbappe/mbappe.png",
    "url": "mbappe.html",
    "nuevo": true,
    "fecha_agregado": "2026-08-07",
    "es_novedad": true,
    "en_oferta": true
  },
  {
    "id": "intermiami-messi",
    "nombre": "Inter Miami - Messi #10",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Messi/Messi.png",
    "url": "Messi.html",
    "nuevo": false,
    "fecha_agregado": "2026-08-30",
    "es_novedad": true,
    "en_oferta": false
  },
  {
    "id": "lamine-barcelona",
    "nombre": "FC Barcelona Temporada 2025-2026 Lamine Yamal #10",
    "categoria": "futbol",
    "precio": 17,
    "precio_anterior": 20,
    "moneda": "USD",
    "imagen": "Futbol/Barcelona/Yamal.png",
    "url": "Lamine.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": true
  },
  {
    "id": "pedri-barcelona",
    "nombre": "FC Barcelona Temporada 2025 Pedri #8",
    "categoria": "futbol",
    "precio": 18,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Barcelona/Pedribeige.png",
    "url": "pedrib.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "pedri-espana",
    "nombre": "Pedri - España Alternativa",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Pedriesp.png",
    "url": "Pedri.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "raphinha-barcelona",
    "nombre": "FC Barcelona - Raphinha #11",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/Barcelona/raphinha.png",
    "url": "raphinha.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "realmadrid-bellingham",
    "nombre": "Real Madrid - Bellingham #5",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/bellingham.png",
    "url": "realmadrid-bellingham.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "realmadrid-cucurella",
    "nombre": "Real Madrid - Cucurella #17",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/cucurella-front.jpg",
    "url": "realmadrid-cucurella.html",
    "nuevo": false,
    "fecha_agregado": "2026-08-30",
    "es_novedad": true,
    "en_oferta": false
  },
  {
    "id": "realmadrid-cucurella-alt",
    "nombre": "Real Madrid - Cucurella #17 (Alternativa)",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/cucurella-alt-front.jpg",
    "url": "realmadrid-cucurella-alt.html",
    "nuevo": false,
    "fecha_agregado": "2026-08-30",
    "es_novedad": true,
    "en_oferta": false
  },
  {
    "id": "realmadrid-mbappe",
    "nombre": "Real Madrid - Mbappé #10",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/mbappe-back.jpg",
    "url": "realmadrid-mbappe.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "realmadrid-vinijr",
    "nombre": "Real Madrid - Vini Jr. #7",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/vinijr-back.png",
    "url": "realmadrid-vinijr.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "realmadrid-vinijr-alt",
    "nombre": "Real Madrid - Vini Jr #7 (Alternativa)",
    "categoria": "futbol",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Futbol/RealMadrid/vinialt.png",
    "url": "Altvinijr.html",
    "nuevo": false,
    "fecha_agregado": "2026-08-30",
    "es_novedad": true,
    "en_oferta": false
  },
  {
    "id": "santos-neymar",
    "nombre": "Santos - Neymar #10",
    "categoria": "futbol",
    "precio": 18,
    "precio_anterior": 20,
    "moneda": "USD",
    "imagen": "Futbol/Neymarsantos.png",
    "url": "ney.html",
    "nuevo": true,
    "fecha_agregado": "2026-08-07",
    "es_novedad": true,
    "en_oferta": true
  },

  // ===== BÉISBOL =====
  {
    "id": "clemente-pr",
    "nombre": "Puerto Rico - Roberto Clemente #21",
    "categoria": "beisbol",
    "precio": 25,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Beisbol/PR/clemente.png",
    "url": "Clemente.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "mariano-rivera",
    "nombre": "New York Yankees - Mariano Rivera #42",
    "categoria": "beisbol",
    "precio": 40,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Beisbol/Mariano/mariano42.png",
    "url": "Mariano.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "pujols-angels",
    "nombre": "Los Angeles Angels - Pujols #5",
    "categoria": "beisbol",
    "precio": 25,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Beisbol/Angels/pujols.png",
    "url": "pujols.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },

  // ===== GORRAS =====
  {
    "id": "cuba-gorra",
    "nombre": "Cuba",
    "categoria": "gorras",
    "precio": 10,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Gorras/Cuba.png",
    "url": "Cuba.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "detroit-gorra",
    "nombre": "Detroit",
    "categoria": "gorras",
    "precio": 10,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Gorras/Detroit.png",
    "url": "Detroit.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "pr-gorra",
    "nombre": "Puerto Rico",
    "categoria": "gorras",
    "precio": 10,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Gorras/Pr.png",
    "url": "Pr.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },

  // ===== PERFUMES =====
  {
    "id": "dhabana-hombre",
    "nombre": "D HABANA - Eau de Toilette",
    "categoria": "perfumes",
    "precio": 20,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Perfumes/DeHabana/hombre.png",
    "url": "DHabanahombre.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },
  {
    "id": "dhabana-mujer",
    "nombre": "D HABANA - Eau de Parfum",
    "categoria": "perfumes",
    "precio": 25,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Perfumes/DeHabana/mujer.png",
    "url": "DHabanamujer.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },

  // ===== ACCESORIOS =====
  {
    "id": "toalla-alemania",
    "nombre": "Toalla Deportiva Selección Alemania (DFB)",
    "categoria": "accesorios",
    "precio": 8,
    "precio_anterior": 10,
    "moneda": "USD",
    "imagen": "Accesorios/Toallas/toalla-alemania.png",
    "url": "toalla-alemania.html",
    "nuevo": true,
    "fecha_agregado": "2026-06-15",
    "es_novedad": true,
    "en_oferta": true
  },
  {
    "id": "toalla-brasil",
    "nombre": "Toalla Deportiva Selección Brasil (CBF)",
    "categoria": "accesorios",
    "precio": 9,
    "precio_anterior": 10,
    "moneda": "USD",
    "imagen": "Accesorios/Toallas/toalla-brasil.png",
    "url": "toalla-brasil.html",
    "nuevo": true,
    "fecha_agregado": "2026-06-15",
    "es_novedad": true,
    "en_oferta": true
  },
  {
    "id": "toalla-francia",
    "nombre": "Toalla Deportiva Selección Francia (FFF)",
    "categoria": "accesorios",
    "precio": 10,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Accesorios/Toallas/toalla-francia.png",
    "url": "toalla-francia.html",
    "nuevo": true,
    "fecha_agregado": "2026-06-15",
    "es_novedad": true,
    "en_oferta": false
  },

  // ===== COMBOS =====
  {
    "id": "combo-pr",
    "nombre": "Combo Camisa + Gorra Puerto Rico",
    "categoria": "combos",
    "precio": 30,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Imagen/Combopr.png",
    "url": "Combopr.html",
    "nuevo": true,
    "fecha_agregado": "2026-08-06",
    "es_novedad": true,
    "en_oferta": false
  },
  {
    "id": "dhabana-set",
    "nombre": "D HABANA - Set Hombre y Mujer",
    "categoria": "combos",
    "precio": 40,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Combos/DeHabana1.png",
    "url": "dehabana.html",
    "nuevo": false,
    "fecha_agregado": "2026-06-15",
    "es_novedad": false,
    "en_oferta": false
  },

  // ===== CUIDADO =====
  {
    "id": "melao-desodorante",
    "nombre": "Melao - Desodorante",
    "categoria": "cuidado",
    "precio": 0.7,
    "precio_anterior": null,
    "moneda": "USD",
    "imagen": "Cuidado/Melao.png",
    "url": "Melao.html",
    "nuevo": true,
    "fecha_agregado": "2026-08-07",
    "es_novedad": true,
    "en_oferta": false
  }
];
